import crypto from "crypto";

function getEncryptionKey(): Buffer {
  const keyBase64 = process.env.ENCRYPTION_KEY;
  if (!keyBase64) {
    throw new Error("ENCRYPTION_KEY environment variable is not configured.");
  }
  const keyBuffer = Buffer.from(keyBase64, "base64");
  if (keyBuffer.length !== 32) {
    throw new Error("ENCRYPTION_KEY must be a 32-byte base64 string.");
  }
  return keyBuffer;
}

/**
  * Encrypts plainText using AES-256-GCM.
  * Returns a base64 string containing: [12-byte IV][16-byte AuthTag][Ciphertext].
  */
export function encrypt(plainText: string): string {
  const key = getEncryptionKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  
  const encrypted = Buffer.concat([
    cipher.update(plainText, "utf8"),
    cipher.final(),
  ]);
  const authTag = cipher.getAuthTag();

  return Buffer.concat([iv, authTag, encrypted]).toString("base64");
}

/**
  * Decrypts AES-256-GCM base64 ciphertext generated by encrypt().
  */
export function decrypt(cipherText: string): string {
  const key = getEncryptionKey();
  const buffer = Buffer.from(cipherText, "base64");
  if (buffer.length < 28) {
    throw new Error("Invalid ciphertext buffer length.");
  }

  const iv = buffer.subarray(0, 12);
  const authTag = buffer.subarray(12, 28);
  const encryptedText = buffer.subarray(28);

  const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv);
  decipher.setAuthTag(authTag);

  return (
    decipher.update(encryptedText, undefined, "utf8") + decipher.final("utf8")
  );
}

/**
  * Generates deterministic HMAC-SHA256 hash of lowercased and trimmed value.
  * Used ONLY for lookups and uniqueness checks — never decrypted or returned.
  */
export function hashForLookup(value: string): string {
  const secret = process.env.LOOKUP_HASH_SECRET;
  if (!secret) {
    throw new Error("LOOKUP_HASH_SECRET environment variable is not configured.");
  }
  const normalized = value.trim().toLowerCase();
  return crypto.createHmac("sha256", secret).update(normalized).digest("hex");
}

/**
  * Generates HMAC-SHA256 hash of a refresh token.
  * Used for refresh token storage in DB — raw token is never saved.
  */
export function hashToken(token: string): string {
  const secret = process.env.REFRESH_TOKEN_HASH_SECRET;
  if (!secret) {
    throw new Error("REFRESH_TOKEN_HASH_SECRET environment variable is not configured.");
  }
  return crypto.createHmac("sha256", secret).update(token).digest("hex");
}
